name: PanditBOT
'on':
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Compression
        id: brotli
        uses: charlesworth/compress-action@1.0.0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - name: Updating JSON
        run: |
          cp archive.tar.gz ../
          cd ..
          tar -xvf archive.tar.gz
          cd pt*
          git config user.name PtPrashantTripathi
          git config user.email ptprashanttripathi@outlook.com
          git add .
          git commit -m "🤖[PanditBot] Updating Repos Data"
          git push --quiet
